export type RouteName = 'Intro'
	| 'More'
	| 'TellFriend'
	| 'TombRaider'
	| 'SelectList'
	| 'PointOnMap'
	| 'HelpCenter'
	| 'About'
	| 'Register'
	| 'Login'
	| 'ResetPassword'
	| 'Profile'
	| 'UpdateProfile'
	| 'UpdatePassword'
	| 'Home';
